browser=chrome
url=https://rahulshettyacademy.com/client
host=localhost
port=8080
dbName=EmployeeDB
dbUser=root
dbPassword=srishtidatabase

userEmail=dummyemailsrishti@gmail.com
userPassword=Dummyemail2@

